### ISSUE TITLE
Feedback for “WI installed the latest version and it doesn't work with an errorindows 1-click installer”

### ISSUE THREAD

**Issue by vivalavida1977** [Sanster/lama-cleaner-docs#17]
Error at startup:
lama-cleaner: error: torch.cuda.is_available() is False, please use --device cpu or check your pytorch installation

Error during package installation:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.18 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rembg 2.0.32 requires click>=8.1.3, but you have click 7.1.2 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.14.1+cu117 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.18 requires torch==2.0.0, but you have torch 1.13.1+cu117 which is incompatible.

**Comment by Sanster** [comment]
Thanks for reporting the error, I think we can ignore the click version conflict as it doesn't affect usage.

However, the torch version is a real problem, mainly because the latest xformers (0.0.18) depend on torch 2.0(I was using an old python pypi source to do test so I didn't find this problem.)

Unzip the zip package again and replace the contents of `win_config.bat` with the following to solve the torch problem

```bash
@echo off

set PATH=C:\Windows\System32;%PATH%

@call installer\Scripts\activate.bat

@call conda-unpack

@call conda install -y -c conda-forge cudatoolkit=11.7
@call pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
@call pip3 install xformers==0.0.16
@call pip3 install -U lama-cleaner
@call lama-cleaner --install-plugins-package

@call lama-cleaner --config-installer --installer-config %0\..\installer_config.json

PAUSE
```

**Comment by vivalavida1977** [comment]
Thanks for the quick reply!
We solved the problem successfully 😊.
Thank you for this very useful app!

**Comment by ZZZephyriusss** [comment]
hello ! i have just purchase the lame cleaner but 
![aaaaaaaaaaaaa](https://github.com/Sanster/lama-cleaner-docs/assets/131444123/c7c1922a-1b21-4ccc-a34c-1d7fa5e505f9)

 i have copy pate your fix but still have the same error

**Comment by Sanster** [comment]
> hello ! i have just purchase the lame cleaner but ![aaaaaaaaaaaaa](https://user-images.githubusercontent.com/131444123/239847832-c7c1922a-1b21-4ccc-a34c-1d7fa5e505f9.png)
> 
> i have copy pate your fix but still have the same error

Do you have a nvidia graphics card on your computer? If not, you can change all devices to cpu in the configuration (installer_config.json)

**Comment by ZZZephyriusss** [comment]
yes i have an Nvidia GPU ( RTX2060 12go) , and my install of stable diffusion detect cuda with no problem. Maybe the programm is looking to pytorch in the wrong place ? Tell me what test i can do to find the problem, really want to test your super app !
thanks for your time.

**Comment by Sanster** [comment]
Could you please check what version of PyTorch is being used by the stable diffusion webui? After confirming the version, you can switch to the same version of PyTorch.

**Comment by Sanster** [comment]
Hardware/driver capable of running 2.0.0+cu118 should also be able to run 1.13.1+cu117, so now Lama Cleaner can correctly recognize the GPU in its environment? 

This directory is for stable-diffusion-webui, what operation did you perform on Lama Cleaner to encounter this error?
